
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "Wed 05 Jan 2022 02:59:17 PM CST",
 "dirty": false,
 "error": null,
 "full-revisionid": "060f878f90a09be8d1945c378d1df8c533d4e1de",
 "version": "1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
