
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-01T01:48:40-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "300ad2700c5f4464ffff136b768f5b0cb2602898",
 "version": "0+untagged.1301.g300ad27.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
