coverage:
  range: "0...100"
  status:
    patch:
      default:
        target: 0
        threshold: 100
    project:
      default:
        target: 0
        threshold: 100
      patch:
        target: 0
        threshold: 100
      unittests:
        target: 0
        threshold: 100
        flags:
          - "unittests"
      smoketests:
        target: 0
        threshold: 100
        flags:
          - "smoketests"
  ignore:
    - "pynets/templates/*"
    - "pynets/rsnrefs/*"
    - "pynets/core/atlases/*"
    - "pynets/core/labelcharts/*"
    - "pynets/runconfig.yaml"
    - "pynets/conftest.py"
    - "pynets/cloudconfig.json"
    - "pynets/bidsconfig.json"
    - "pynets/stats/nodal_graph_measures.yaml"
    - "pynets/stats/global_graph_measures.yaml"
    - "docs/*"
    - "tests/*"
    - "pynets/__about__.py"
    - "pynets/_version.py"
    - "get_version.py"
    - "versioneer.py"
    - "setup.py"
    - "*__init__*"
    - "*__pycache__*"
    - "*.json"
    - "setup.cfg"
    - "tox.ini"
    - "requirements.txt"
    - "README.rst"
    - "README.md"
    - "MANIFEST.ini"
    - "Makefile"
    - "Dockerfile"
    - "CONTRIBUTING.rst"
    - "AUTHORS.rst"
    - "docker/*"
    - "pynets/cli/*"
    - "pynets/plotting/connectogram.js"
    - "pynets/plotting/FD_graph.json"
    - "pynets/plotting/fdg.js"
    - "pynets/plotting/index.html"
    - "pynets/stats/netmotifs.py"
    - "pynets/stats/benchmarking.py"
    - "pynets/stats/embeddings.py"
    - "pynets/stats/prediction.py"
    - "pynets/stats/utils.py"
    - "pynets/core/cloud_utils.py"
    - "pynets/registration/register.py"
    - "pynets/core/interfaces.py"

codecov:
  token: d62ad7b3-39a6-4657-a2e3-6acf2362d36d
