coverage:
  range: "0...100"
  status:
    patch:
      default:
        target: 0
        threshold: 100
    project:
      default:
        target: 0
        threshold: 100
      patch:
        target: 0
        threshold: 100
      unittests:
        target: 0
        threshold: 100
        flags:
          - "unittests"
      smoketests:
        target: 0
        threshold: 100
        flags:
          - "smoketests"
  ignore:
	- "*__init__*"
	- "*__pycache__*"
	- "docs/*"
	- "*.json"
	- "*.circleci/*"
	- "*.github/*"
	- "*.test_durations"
	- "*.gitignore"
	- "*.gitattributes"
	- "setup.py"
	- "setup.cfg"
	- "tox.ini"
	- "requirements.txt"
	- "optional-requirements.txt"
	- "pytest.ini"
	- "README.rst"
	- "README.md"
	- "NOTICE"
	- "MANIFEST.ini"
	- "Makefile"
	- "Dockerfile"
	- "CONTRIBUTING.rst"
	- "AUTHORS.rst"
	- "docker/*"
	- "licenses/*"
	- "data/*"
	- "get_version.py"
	- "versioneer.py"
	- "pynets/__about__.py"
	- "pynets/_version.py"
	- "pynets/__init__.py"
	- "pynets/advanced.yaml"
	- "pynets/citations.py"
	- "pynets/cli/*"
    - "pynets/core/tests/*"
    - "pynets/core/__init__.py"
    - "pynets/dmri/tests/*"
    - "pynets/dmri/__init__.py"
    - "pynets/fmri/tests/*"
    - "pynets/fmri/__init__.py"
    - "pynets/plotting/tests/*"
    - "pynets/plotting/__init__.py"
    - "pynets/registration/tests/*"
    - "pynets/registration/__init__.py"
    - "pynets/statistics/tests/*"
    - "pynets/statistics/individual/*.yaml"
    - "pynets/statistics/individual/__init__.py"
    - "pynets/statistics/group/__init__.py"
    - "pynets/statistics/__init__.py"
    - "pynets/templates/__init__.py"
    - "pynets/templates/*/*"

codecov:
  token: d62ad7b3-39a6-4657-a2e3-6acf2362d36d
